services:

  server:
    container_name: server_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - au_network
    volumes:
      - ./media:/app/media
    env_file:
      - .env

networks:
  au_network:
    driver: bridge